import { useState, useEffect, useRef, useCallback } from 'react';
import ApiService from '../services/apiService';

export const useMidpData = () => {
  const [midps, setMidps] = useState([]);
  const [loading, setLoading] = useState(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  const loadMidps = useCallback(async () => {
    setLoading(true);
    try {
      const midpData = await ApiService.getAllMIDPs();
      if (!mountedRef.current) return;
      setMidps(midpData.data || []);
    } catch (error) {
      if (mountedRef.current) console.error('Failed to load MIDP data:', error);
    } finally {
      if (mountedRef.current) setLoading(false);
    }
  }, []);

  const createMidp = async (midpData) => {
    await ApiService.autoGenerateMIDPAll({
      projectName: midpData.projectName,
      description: midpData.description
    });
    await loadMidps();
    return { autoGenerated: true };
  };

  return {
    midps,
    loading,
    loadMidps,
    createMidp
  };
};